### ISSUE TITLE
Possible corruption of global flags

### ISSUE THREAD

**Issue by dobacco** [jans0n/RewritePlusImprovementPatch#1]
Can you add to the readme that there is potential of global flags getting corrupted when updates are pushed to the staging branch. To prevent future updates from breaking it further, disable automatic updates on Steam (This also means they won't see any fixes to text/images/etc).

Sekai Project and VisualArts can't support or endorse third party patches, so if people are going to make them please make it clear that they may lead to issues that we can't help with.

Thanks!

**Comment by jans0n** [comment]
Done. I plan on switching back to the non staging branch version of the game for the patch when all the bug fixes are pushed there.
