### ISSUE TITLE
new problem with video

### ISSUE THREAD

**Issue by Takeru1000** [jans0n/RewritePlusImprovementPatch#10]
I arrived to the scene with the teasing song about Yoshino. the video starts, unlike the previous case with the OP, but it looks bad and a bit jerky.

**Comment by Takeru1000** [comment]
> I arrived to the scene with the teasing song about Yoshino. the video starts, unlike the previous case with the OP, but it looks bad and a bit jerky.

the video in fine outside the game as ever with MPV and VLC

**Comment by jans0n** [comment]
Try using MCI

**Comment by Takeru1000** [comment]
> Try using MCI

i'm using MCI
