### ISSUE TITLE
Incorrect sound file names in Shizuru route

### ISSUE THREAD

**Issue by JenXIII** [jans0n/RewritePlusImprovementPatch#11]
Game attempts to play files Shizuhassin, Shizubike, Shizubraking, and probably a few others I didn't get to, but files by those names don't exist.  The SFX play properly on the base version.

**Comment by jans0n** [comment]
Are you sure you're using the latest version?

**Comment by JenXIII** [comment]
Ah, that was it.  I'd last updated on December 23rd and didn't notice there was a new release since there was still only one release listed.  Sorry for the trouble
