### ISSUE TITLE
Suzuki Bond name possibly got censored by Sekai after last update

### ISSUE THREAD

**Issue by Darken-kun** [jans0n/RewritePlusImprovementPatch#12]
It seems Suzuki Bond (Kotarou's spy name) was modified in game by Sekai due to "trademarks concerns", as stated in their patch notes.

<img width="296" alt="1" src="https://user-images.githubusercontent.com/21168806/151562762-6922f9fb-2188-454d-b4b8-0d7b126c1e2f.png">

<img width="261" alt="2" src="https://user-images.githubusercontent.com/21168806/151563092-f78883b4-2cc3-46be-82e3-7d43c989c236.png">

<img width="442" alt="3" src="https://user-images.githubusercontent.com/21168806/151563820-7af25ef2-c0a2-40a5-bdec-c27a0df19252.png">

**Comment by Darken-kun** [comment]
@jans0n Could you check the game files to see if they actually changed Suzuki Bond to some other name and, if that's the case, update the patch to include back the original spy name?

**Comment by jans0n** [comment]
I get results when I search for the name in the files.

**Comment by Darken-kun** [comment]
Okay, thanks for checking it.
