### ISSUE TITLE
Logical errors in Lucia Route scene

### ISSUE THREAD

**Issue by R1kaB3rN** [jans0n/RewritePlusImprovementPatch#13]
In the Lucia route, when Lucia is at Kotarou's house, there's some text that is inconsistent with the 18+ CG. In the Steam edition, Kotarou hands Lucia a shirt, she dresses in it, then we're showed the scene . But with this patch, we're showed the 18+ CG so the line doesn't logically fit.

The line is "Dressed in just a T-shirt that I brought out for her, Class Rep recalls the dream she just had." This can be a simple fix by just deleting everything up until "Class Rep recalls the dream she just had."

**Comment by jans0n** [comment]
Fixed
