### ISSUE TITLE
Video files corrupted when downloading the patch from the source code

### ISSUE THREAD

**Issue by Darken-kun** [jans0n/RewritePlusImprovementPatch#2]
I couldn't reproduce the OPs, the ED and the Yoshino video, neither on Rewrite nor directly on the folder. When I checked possibly why, I noticed the files only had a few bytes each. Then I noticed I had to manually download them instead (maybe because the videos are too big) by going [here](https://github.com/jans0n/RewritePlusImprovementPatch/tree/main/mov) and clicking individually on them.

I wonder if there isn't a way to overcome this, since most people are just going to download the files as .ZIP from the source code and extract them on the Rewrite+ folder, just to later find out they won't reproduce. Perhaps you need to create a [**release**](https://github.com/jans0n/RewritePlusImprovementPatch/releases) for this patch in order to enable people to download the videos with their full size? I'm not really used to GitHub, so I don't know for sure.

**Comment by jans0n** [comment]
Thanks for pointing this out.

**Comment by Darken-kun** [comment]
No problem. Creating releases not only fixes that issue, but is also useful to have multiple versions of the patch avaliable to download. In case this new update Sekai is preparing for Rewrite+ turns out to be incompatible with your patch, you can create a new release compatible with it, and people can choose between the two of them depeding on which version of the game they have.
