### ISSUE TITLE
Japanese honorifics and the like

### ISSUE THREAD

**Issue by SwissCheesecake** [jans0n/RewritePlusImprovementPatch#3]
This is more of a request than a problem, so... let's cut to the chase. I purchased the visual novel recently and was incredibly disappointed with the absence of Japanese honorifics in the Sekai Project translation. I was kind of expecting this, but it's still sad to see that there hasn't been any change in their policy. So, the question is: will there be some sort of restoration of this wrong text in this patch eventually? I know this patch is new and that the visual novel has just come out as well, but still, I would like to know if there might be this fix in the near future or if it's asking too much. Thank you in advance for your initiative in wanting to bring a more pleasant experience for us, fans of visual novels in the West. Thank you very much.

**Comment by jans0n** [comment]
It would be a big undertaking. I would have to manually go in and change every line, I'll think about it but it's probably not worth it.
