### ISSUE TITLE
Can't open the game after applying the patch

### ISSUE THREAD

**Issue by GonXdramon** [jans0n/RewritePlusImprovementPatch#4]
---------------------------
Rewrite+
---------------------------
[2021/12/24 00:14:23.0408] 

フォントファイル KosugiMaru-Regular.ttf が見つかりませんでした。

[Support Info]
You can copy this message by pressing Ctrl+C on your keyboard.
---------------------------
OK   
---------------------------

If it's a font missing, I already download it.

**Comment by jans0n** [comment]
There should be a tff font file in the "dat" directory inside your Rewrite+ installation folder. Is it there?

**Comment by GonXdramon** [comment]
I have the dat directory but not a tff font file.

**Comment by jans0n** [comment]
bery odd, the patch shouldn't interfere with it. Verify your game files on steam and reinstall the patch.

**Comment by GonXdramon** [comment]
This happened after I put the  SceneEN.pck, GameexeEN.dat, and mov folder. I did not put the g00 folder since I don't want the CGs.

And no, reinstalling the patch does not work.

**Comment by jans0n** [comment]
Download the [font](https://drive.google.com/file/d/1Un3pIzJyym6Qf2Rs86kK6lrjJHFyD1hG/view?usp=sharing) and place it in your "dat" folder.

**Comment by GonXdramon** [comment]
Alright it worked! The thing is, there are like 3 versions of that font and I did try to put them in the dat folder,1 at a time.

And I'm pretty sure the one you sent was the same one I had downloaded. Either way it worked, thank you and good work!

**Comment by Hiraeth1907** [comment]
The link is down, can you upload it again, please?

**Comment by Hiraeth1907** [comment]
It worked perfectly, thanks!
