### ISSUE TITLE
Subtitles in videos

### ISSUE THREAD

**Issue by AEBus** [jans0n/RewritePlusImprovementPatch#5]
Hello, you can just copy ***.ass** files with subtitles in **mov** folder, change Movie Player to **MCI** in game settings, and subtitles will be shown
Dont need include a whole videos in the patch =)

To have this option enabled by default, you must also place a **system.ini** file in the **savedata_en** folder with the following contents:

```
#D3D.ADAPTER_NO = 0
#D3D.HARDWARE_VERTEX = 1
#D3D.PRESENT_INTERVAL = 1
#D3D.USE_MIPMAP = 1
#D3D.WIPE_BUFFER_COUNT = 2
#DS.PLAY_SILENT_SOUND = 0
#MOVIE_TYPE = 0
```

**Comment by jans0n** [comment]
I am aware, but it's easier to just hardsub because not everyone is going to have the fonts installed. The videos also have extremely low audio bitrate which this patch fixes.

**Comment by AEBus** [comment]
Well, If you insist =) I won't argue with you.

**Comment by jans0n** [comment]
These videos are technically just a placeholder anyway. Sekai Project plans on adding their own after the holidays.
