### ISSUE TITLE
Possible Issue with some repalced lines

### ISSUE THREAD

**Issue by alemilla** [jans0n/RewritePlusImprovementPatch#8]
There are some lines (17 in total although some are repeated) in seen05001 that are replaced (Sizu->Shizu) on your patch and I think may provoke issues with the game.

- sizuhassin
- sizubraking
- sizubike
- sizubraking
- sizuguns
- sizubike
- sizugunl
- sizuhassin
- sizugunl
- sizubike
- sizubraking
- sizugunl
- sizugunl
- sizubike
- sizuhassin
- sizubraking
- sizuhassin

I think this can be solved if when replacing you have selected the "Match Mayus/minus" or something like that (I don't have my Notepad++ in English so maybe it is not exactly written like this) when making the mass replace. When I try to do it like this, these 17 aren't touched while all the rest change.

**Comment by jans0n** [comment]
Thanks for pointing this out. I used a different program than notepad when I did the changes and I didn't see any of those. I will double check tomorrow.
