### ISSUE TITLE
Problem viewing the OP

### ISSUE THREAD

**Issue by Takeru1000** [jans0n/RewritePlusImprovementPatch#9]
I have [problems viewing the OP. i downloaded MPV and set it as default player for all videos and out of the game video files look good. but in-game no, i tried with both settings.

![2](https://user-images.githubusercontent.com/96659648/147399399-a690f2b9-cb36-4e99-92ce-ac7e7f40f9f0.png)

![1](https://user-images.githubusercontent.com/96659648/147399405-c60ba93b-dc58-4fbd-8ec8-ea96c51964ff.png)

**Comment by jans0n** [comment]
Download the [Combined Community Codec Pack](https://www.majorgeeks.com/files/details/cccp_(combined_community_codec_pack).html) and try again.

**Comment by Takeru1000** [comment]
> Download the [Combined Community Codec Pack](https://www.majorgeeks.com/files/details/cccp_(combined_community_codec_pack).html) and try again.

If i use MCI in the movie setting i have this(the screen below) for both MPV and CCCP(I always use this in general) and the game skip the OP if i use the default setting in-game(windows media player). i don't known what MCI is
![3](https://user-images.githubusercontent.com/96659648/147423489-42a7f862-9ce1-4358-82a6-9277c7b72079.png)

but for CCCP and other player i have problem outside game too
![4](https://user-images.githubusercontent.com/96659648/147423704-8c8945eb-973b-4280-9e91-92804d60cfca.png)

**Comment by jans0n** [comment]
Odd, I honestly don't know what would be causing this, I don't have any problem playing the videos in-game. Although I doubt it will change anything, what happens when you switch your system locale to Japan?

**Comment by Takeru1000** [comment]
> Odd, I honestly don't know what would be causing this, I don't have any problem playing the videos in-game. Although I doubt it will change anything, what happens when you switch your system locale to Japan?

Was already in Japan. In the game you use MCI in movie setting? If yes I don't touch it anymore

**Comment by jans0n** [comment]
Yes, I use MCI, the videos don't play if I don't.

**Comment by Takeru1000** [comment]
> Yes, I use MCI, the videos don't play if I don't.

Ok this way I need half or the test. This patch work on the original version on steam?

**Comment by jans0n** [comment]
Yes

**Comment by Axsoul994** [comment]
![image](https://user-images.githubusercontent.com/96715286/147441397-ea2f4413-76ab-492c-98e4-59f1e6902b7e.png)
After using this patch this now pops up when i launch the game

**Comment by Takeru1000** [comment]
> ![image](https://user-images.githubusercontent.com/96715286/147441397-ea2f4413-76ab-492c-98e4-59f1e6902b7e.png) After using this patch this now pops up when i launch the game

Download the font and put it in the dat folder of the game
[https://fonts.google.com/specimen/Kosugi+Maru](url)

**Comment by Takeru1000** [comment]
> Yes

I tried to set the OP to open the file with VLC, MPC HC, MPC HC 64 bit, WMP and MPV. Outside the game only VLC and MPV open the file correctly. 
The game is on MCI and this error appears when trying to load the OP
![147423489-42a7f862-9ce1-4358-82a6-9277c7b72079](https://user-images.githubusercontent.com/96659648/147459186-63d1c6f6-8fbb-42be-8ad6-d353e0438a00.png)

for the setting of PC i have this
![5](https://user-images.githubusercontent.com/96659648/147459663-d76e515c-ecfb-40f7-8ee7-46dfb1f658ea.png)
![6](https://user-images.githubusercontent.com/96659648/147459936-c5c18997-490e-43ca-8814-c8cadfa02206.png)

**Comment by jans0n** [comment]
Does it play if you put this in your mov folder? https://drive.google.com/file/d/1vcQ4asKsR9RMA1X5VgdNlHpkz2ZO-2vj/view?usp=sharing

**Comment by Takeru1000** [comment]
> Does it play if you put this in your mov folder? https://drive.google.com/file/d/1vcQ4asKsR9RMA1X5VgdNlHpkz2ZO-2vj/view?usp=sharing

yep this work fine! i don't known for the other three, i'm in the common route now, very distant from the moon route or end

**Comment by jans0n** [comment]
Download the latest release, it should fix all issues with the videos
